### ISSUE TITLE
模板中数组添加两个对象时词法解析会出错

### ISSUE THREAD

**Issue by rainfore** [regularjs/regular#144]
这种情况OK：
```xml
<chart series={[{ key: 'reading', name: '阅读量' }]} />
```

加一个object就会报错：
```xml
<chart series={[{ key: 'reading', name: '阅读量' }, { key: 'praise', name: '点赞数' }]} />
```

错误日志：
```log
regular.min.js:1 Uncaught Error: Parse Error: Unrecoginized Token:
[1] ..
[2] ..ons', name: '收藏数' }]} />
                          ^^^


    at i.v.error (https://regular-ui.github.io/v0.2/vendor/regular.min.js:1:30622)
    at i.v.lex (https://regular-ui.github.io/v0.2/vendor/regular.min.js:1:30449)
    at new r (https://regular-ui.github.io/v0.2/vendor/regular.min.js:2:1841)
    at e.y (https://regular-ui.github.io/v0.2/vendor/regular.min.js:1:1709)
    at new e (https://regular-ui.github.io/v0.2/vendor/regular.min.js:2:10681)
    at file:///Users/netease/Projects/GitHub/RGUI2/ui-chart/doc/chart/index.html:163:21
    at file:///Users/netease/Projects/GitHub/RGUI2/ui-chart/doc/chart/index.html:171:3v.error @ regular.min.js:1v.lex @ regular.min.js:1r @ regular.min.js:2y @ regular.min.js:1e @ regular.min.js:2(anonymous function) @ index.html:163(anonymous function) @ index.html:171
```

**Comment by fengzilong** [comment]
https://github.com/regularjs/regular/pull/205
这个问题在这次 pr 里面已经修复了，对应的 regular 版本是 0.6.0
